apiVersion: apps/v1

kind: Deployment

metadata:
  name: node-hd-deployment
  labels:
    app: node-hd-deployment

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-hd-app
  template:
    metadata:
      labels:
        app: node-hd-app
    spec:
      containers:
      - name: node-container
        image: node:10-alpine
        ports:
        - containerPort: 7777
        volumeMounts:
        - mountPath: /node-app
          name: node-app-hd-volume
        command: ["/bin/sh", "-c"]
        args: ["npm install && node /node-app/server.js"]
      restartPolicy: Always

      volumes:
      - name: node-app-hd-volume
        hostPath:
          path: /Users/FoysalOsmany/Work/Countly/Dev/countly-stream/helm/helm-demo
          type: Directory
